# Generated by Django 4.2.18 on 2025-01-17 02:29

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('auth_42', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('xp', models.IntegerField(default=0)),
                ('clan', models.CharField(choices=[('VERTEX', 'Vertex'), ('RAIDERS', 'Raiders'), ('PHANTOM', 'Phantom'), ('VIGILANTS', 'Vigilants')], default='VERTEX', max_length=255)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('is_first_login', models.BooleanField(default=True)),
                ('is_2fa_enabled', models.BooleanField(default=False)),
                ('two_factor_secret', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clan_logo', models.URLField(blank=True, null=True)),
                ('match_win', models.IntegerField(default=0)),
                ('match_lose', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(blank=True, default=0.0)),
                ('tournamentsWon', models.IntegerField(default=0)),
                ('pointsScored', models.IntegerField(default=0)),
                ('longestStreak', models.IntegerField(default=0)),
                ('gameCount', models.IntegerField(default=0)),
                ('clanDuration', models.IntegerField(default=0)),
                ('achievment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('UNSTOPPABLE', 'unstoppable'), ('FIRST BLOOD', 'first blood'), ('LOYALIST', 'loyalist'), ('CONQUEROR', 'conqueror')], max_length=50), blank=True, default=list, size=None)),
                ('matchHistory', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None)),
                ('isInGame', models.BooleanField(default=False)),
                ('friends', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_score', models.IntegerField(default=0)),
                ('opponent_score', models.IntegerField(default=0)),
                ('match_date', models.DateTimeField(auto_now_add=True)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_opponent', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
