FROM owasp/modsecurity-crs:4.8.0-nginx-alpine-202411071011
USER root

RUN mkdir -p /nginx/ssl && \
    chown -R nginx:nginx /nginx/ssl && \
    chmod 700 /nginx/ssl

WORKDIR /nginx/ssl

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /nginx/ssl/server.key \
    -out /nginx/ssl/server.crt \
    -subj "/"




COPY conf/nginx.conf /etc/nginx/templates/conf.d/default.conf.template

CMD ["nginx", "-g", "daemon off;"]