# Generated by Django 4.2.17 on 2025-01-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=8)),
                ('max_players', models.IntegerField(default=2)),
                ('current_players', models.IntegerField(default=0)),
            ],
        ),
    ]
